/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e4e2e4",
        "on-surface-variant": "#414753",
        "secondary-fixed-dim": "#c7c6cb",
        "surface-bright": "#fcf8fb",
        "secondary": "#5e5e63",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#626267",
        "on-background": "#1b1b1d",
        "on-tertiary-fixed": "#341000",
        "tertiary": "#9b3f00",
        "on-tertiary-container": "#fffaf9",
        "on-primary-fixed": "#001b3f",
        "surface-container-high": "#eae7ea",
        "surface-tint": "#005cbb",
        "tertiary-fixed-dim": "#ffb693",
        "error-container": "#ffdad6",
        "surface-dim": "#dcd9dc",
        "surface-container": "#f0edef",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1a1b1f",
        "primary-fixed-dim": "#abc7ff",
        "surface": "#fcf8fb",
        "error": "#ba1a1a",
        "tertiary-container": "#c25100",
        "background": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "surface-variant": "#e4e2e4",
        "primary": "#0059b5",
        "on-secondary-fixed-variant": "#46464b",
        "on-tertiary-fixed-variant": "#7a3000",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fcfbff",
        "secondary-container": "#e0dfe4",
        "inverse-primary": "#abc7ff",
        "primary-container": "#0071e3",
        "primary-fixed": "#d7e2ff",
        "secondary-fixed": "#e3e2e7",
        "on-surface": "#1b1b1d",
        "surface-container-low": "#f6f3f5",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#00458f",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c6d6",
        "outline": "#717785",
        "on-error-container": "#93000a",
        "inverse-surface": "#303032"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "160px",
        "unit": "8px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-xl": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["19px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
